"""SkillLayer .skilllayer/ persistence infrastructure.

Storage root: <repo>/.skilllayer/
Source of truth: markdown + YAML-like frontmatter (schema: 1)
No PyYAML dependency — minimal key:value parser.
Zero LLM calls in all read and write paths.

Directory layout:
  .skilllayer/
    INDEX.md            — digest, regenerated by every write workflow
    context/
      latest.md         — SaveContextSnapshot (latest-wins, gitignored)
      history/          — rotated snapshots, keep last HISTORY_KEEP
    decisions/
      0001-slug.md      — TrackDecisionLog (append-only, immutable)
    preferences.md      — RememberUserPreferences (upsert per section)
    .state.json         — sequence bookkeeping only, never read by Claude
"""
from __future__ import annotations

import contextlib
import json
import os
import re
import tempfile
import threading
import time
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Iterator

try:  # POSIX only. Windows has no fcntl — see MEMORY_LOCK_CROSS_PROCESS_SUPPORTED.
    import fcntl
except ImportError:  # pragma: no cover - exercised only on non-POSIX platforms.
    fcntl = None  # type: ignore[assignment]

SCHEMA_VERSION = 1
HISTORY_KEEP = 5


# ---------------------------------------------------------------------------
# Timestamps
# ---------------------------------------------------------------------------

def _utc_iso() -> str:
    """ISO-8601 timestamp for frontmatter fields."""
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def _utc_date() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%d")


def _utc_filename_ts() -> str:
    """Compact timestamp safe for filenames.

    Microsecond resolution (not just seconds): under the memory_lock, two
    concurrent save_context_snapshot rotations are serialized, but a
    second-only timestamp could still collide if both land in the same
    wall-clock second, silently overwriting one rotated history file with
    the other. Microseconds make that collision negligible in practice.
    """
    return datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%S%f") + "Z"


# ---------------------------------------------------------------------------
# Cross-process lock over the whole .skilllayer memory transaction boundary
#
# One lock, not one per file: every read-modify-write sequence that touches
# related memory files (e.g. AddTodo's todos.json + .state.json counter +
# INDEX.md) acquires this ONE lock for its full logical transaction, so two
# concurrent processes can never interleave partial updates.
#
# Built on fcntl.flock (POSIX only — this module makes no claim of
# cross-process safety on Windows; MEMORY_LOCK_CROSS_PROCESS_SUPPORTED
# reflects this truthfully rather than silently pretending otherwise). flock
# is scoped to the OS-level open-file-description and is released
# automatically by the kernel the instant the holding process exits for ANY
# reason (normal return, crash, kill -9) — this eliminates the classic
# "stale PID lock file" problem by construction: the lock can never outlive
# its holder, so there is no stale-lock cleanup to implement.
# ---------------------------------------------------------------------------

MEMORY_LOCK_CROSS_PROCESS_SUPPORTED = fcntl is not None
MEMORY_LOCK_FILENAME = ".memory.lock"
DEFAULT_MEMORY_LOCK_TIMEOUT_SECONDS = 10.0
_MEMORY_LOCK_POLL_INTERVAL_SECONDS = 0.05


class MemoryLockTimeoutError(Exception):
    """Raised when the cross-process .skilllayer memory lock could not be
    acquired within the timeout — another process is actively holding it.

    NOT a stale-lock condition: flock is released by the kernel the instant
    its holder's process exits, for any reason including a crash, so a
    timeout here means genuine live contention (a slow or hung concurrent
    writer), never an orphaned leftover lock.
    """

    def __init__(self, skilllayer_dir: Path, timeout: float) -> None:
        self.skilllayer_dir = skilllayer_dir
        self.timeout = timeout
        super().__init__(
            f"Could not acquire the .skilllayer memory lock within {timeout}s "
            f"(another process is actively writing to {skilllayer_dir}). "
            "This is live contention, not a stale lock — the OS releases this "
            "lock automatically the instant its holder exits. Retry the "
            "operation; if it keeps timing out, another process is genuinely "
            "stuck, not merely a leftover lock file."
        )


class _ReentrantLockState(threading.local):
    def __init__(self) -> None:
        self.depth = 0
        self.fd: int | None = None


_LOCK_STATE = _ReentrantLockState()

# Process-local mutual exclusion, separate from the thread-local depth
# bookkeeping above. Two threads in the SAME process racing on memory_lock()
# must never both proceed at once — depth alone cannot provide that, since
# threading.local() gives each thread its own independent depth counter.
# RLock (not Lock) because the reentrant nested-call path above re-enters
# from the SAME thread while already holding it. Keyed by resolved
# .skilllayer directory so two different repositories' locks never
# contend with each other.
_PROCESS_LOCKS_GUARD = threading.Lock()
_PROCESS_LOCKS: dict[Path, threading.RLock] = {}


def _process_lock_for(skilllayer_dir: Path) -> threading.RLock:
    key = skilllayer_dir.resolve()
    with _PROCESS_LOCKS_GUARD:
        lock = _PROCESS_LOCKS.get(key)
        if lock is None:
            lock = threading.RLock()
            _PROCESS_LOCKS[key] = lock
        return lock


@contextlib.contextmanager
def memory_lock(
    skilllayer_dir: Path,
    timeout: float = DEFAULT_MEMORY_LOCK_TIMEOUT_SECONDS,
) -> Iterator[None]:
    """Acquire the whole-store memory lock for one transaction.

    Two layers, acquired in this order (released in reverse):
      1. A process-local threading.RLock, keyed by resolved skilllayer_dir —
         provides real mutual exclusion between THREADS in this process.
         threading.local() depth bookkeeping alone cannot do this: each
         thread has its own independent depth counter, so two threads could
         both see depth==0 and both proceed at once with no serialization.
      2. On POSIX only, fcntl.flock on .memory.lock — provides mutual
         exclusion between PROCESSES. Not attempted on platforms without
         fcntl (see MEMORY_LOCK_CROSS_PROCESS_SUPPORTED); on those platforms
         only same-process/same-thread safety (layer 1) is provided, and
         that fact is not hidden.

    Reentrant within a single thread: a nested memory_lock() call (e.g.
    claim_next_id() invoked from inside add_todo()'s already-held lock) never
    re-flock's — flock is scoped to the open-file-description, not the
    process, so a naive re-open+re-flock from the same thread would
    deadlock against itself. The RLock IS re-acquired on nested calls
    (cheap — natively reentrant for the same thread) purely to keep
    acquire/release symmetric.

    Bounded timeout, shared across both layers (a slow RLock wait eats into
    the time left for the flock wait). Raises MemoryLockTimeoutError if
    either layer is not acquired in time. Release always happens in
    `finally`, including on exception.

    Callers must perform ONLY the transaction's file I/O inside this block —
    no subprocess calls, network access, or other unrelated expensive work.
    """
    skilllayer_dir.mkdir(parents=True, exist_ok=True)
    deadline = time.monotonic() + timeout
    process_lock = _process_lock_for(skilllayer_dir)

    if _LOCK_STATE.depth > 0:
        process_lock.acquire()
        _LOCK_STATE.depth += 1
        try:
            yield
        finally:
            _LOCK_STATE.depth -= 1
            process_lock.release()
        return

    if not process_lock.acquire(timeout=max(deadline - time.monotonic(), 0)):
        raise MemoryLockTimeoutError(skilllayer_dir, timeout)

    try:
        if fcntl is None:
            # No cross-process locking available on this platform. The
            # process_lock above still provides same-process/same-thread
            # mutual exclusion — cross-process safety is NOT claimed here.
            _LOCK_STATE.depth = 1
            try:
                yield
            finally:
                _LOCK_STATE.depth = 0
            return

        lock_path = skilllayer_dir / MEMORY_LOCK_FILENAME
        fd = os.open(str(lock_path), os.O_CREAT | os.O_RDWR, 0o600)
        acquired = False
        try:
            while True:
                try:
                    fcntl.flock(fd, fcntl.LOCK_EX | fcntl.LOCK_NB)
                    acquired = True
                    break
                except BlockingIOError:
                    if time.monotonic() >= deadline:
                        raise MemoryLockTimeoutError(skilllayer_dir, timeout) from None
                    time.sleep(_MEMORY_LOCK_POLL_INTERVAL_SECONDS)
            with contextlib.suppress(OSError):
                os.ftruncate(fd, 0)
                os.write(fd, f"{os.getpid()} {_utc_iso()}\n".encode("utf-8"))
            _LOCK_STATE.depth = 1
            _LOCK_STATE.fd = fd
            try:
                yield
            finally:
                _LOCK_STATE.depth = 0
                _LOCK_STATE.fd = None
        finally:
            if acquired:
                with contextlib.suppress(OSError):
                    fcntl.flock(fd, fcntl.LOCK_UN)
            os.close(fd)
    finally:
        process_lock.release()


# ---------------------------------------------------------------------------
# Atomic write helper — text and JSON, no duplicated safety logic
#
# Write to a temp file in the SAME directory, flush, fsync the file, then
# os.replace() onto the destination (an atomic rename), and best-effort
# fsync the parent directory so the rename is durable across a crash. On any
# failure before the replace, the destination is left completely untouched
# and the temp file is removed — never a truncated or partially-written
# destination file.
# ---------------------------------------------------------------------------

def atomic_write_text(path: Path, text: str, encoding: str = "utf-8") -> None:
    """Atomically write `text` to `path`. Preserves the same encoding and
    universal-newline translation behavior as Path.write_text()."""
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, tmp_name = tempfile.mkstemp(dir=str(path.parent), prefix=f".{path.name}.", suffix=".tmp")
    tmp_path = Path(tmp_name)
    try:
        with os.fdopen(fd, "w", encoding=encoding) as f:
            f.write(text)
            f.flush()
            os.fsync(f.fileno())
        os.replace(tmp_path, path)
    except BaseException:
        with contextlib.suppress(OSError):
            tmp_path.unlink()
        raise
    else:
        with contextlib.suppress(OSError):
            dir_fd = os.open(str(path.parent), os.O_RDONLY)
            try:
                os.fsync(dir_fd)
            finally:
                os.close(dir_fd)


def atomic_write_json(path: Path, data: Any, *, indent: int = 2) -> None:
    """Atomically write `data` as JSON to `path`. See atomic_write_text."""
    atomic_write_text(path, json.dumps(data, indent=indent))


# ---------------------------------------------------------------------------
# Result contract — shared by every user-facing memory workflow result.
#
# status: "healthy" | "warning" | "broken" | "error"
#   healthy — operation completed, no integrity problem. success: true.
#   warning — operation completed, usable result exists, but there is a
#             non-fatal limitation or recoverable condition worth surfacing
#             (e.g. no memory store saved yet). success: true, warnings set.
#   broken  — memory INTEGRITY is invalid; the data must not be trusted as a
#             healthy store (corrupt state/todos file, integrity violation).
#             success: false.
#   error   — the operation could not complete for an environmental or input
#             reason (lock timeout, invalid input, I/O failure) — does not by
#             itself mean the store's data is corrupt. success: false.
#
# Canonical, stable error codes — the SAME spelling everywhere a failure
# surfaces (builder, CLI, direct MCP, generic MCP). Only "broken"-classified
# codes go in _BROKEN_ERROR_CODES; everything else defaults to "error".
# ---------------------------------------------------------------------------

ERROR_MEMORY_LOCK_TIMEOUT = "memory_lock_timeout"
ERROR_MEMORY_STATE_CORRUPT = "memory_state_corrupt"
ERROR_TODOS_STORE_CORRUPT = "todos_store_corrupt"
ERROR_MEMORY_INTEGRITY_BROKEN = "memory_integrity_broken"
ERROR_MEMORY_PERMISSION_DENIED = "memory_permission_denied"
ERROR_MEMORY_IO_ERROR = "memory_io_error"
ERROR_MEMORY_RECORD_NOT_FOUND = "memory_record_not_found"

_BROKEN_ERROR_CODES = frozenset({
    ERROR_MEMORY_STATE_CORRUPT,
    ERROR_TODOS_STORE_CORRUPT,
    ERROR_MEMORY_INTEGRITY_BROKEN,
})


def status_for_error_code(error_code: str | None) -> str:
    """Classify an error_code into the shared status vocabulary.

    error_code is None -> "healthy" by default (callers needing "warning"
    on an otherwise-clean result set status explicitly via finalize_memory_result).
    A code in _BROKEN_ERROR_CODES -> "broken" (data integrity is invalid).
    Any other non-null code -> "error" (operation-level failure, not
    necessarily a corrupt store).
    """
    if error_code is None:
        return "healthy"
    if error_code in _BROKEN_ERROR_CODES:
        return "broken"
    return "error"


def finalize_memory_result(
    result: dict[str, Any],
    *,
    status: str | None = None,
    warnings: list[str] | None = None,
    include_status_field: bool = True,
) -> dict[str, Any]:
    """Stamp success/status/warnings onto a memory-workflow result dict.

    The single place every builder (in this module or in runner/core.py for
    the two read-only workflows that live there) must route its return value
    through, instead of hand-computing `success` at the CLI or MCP layer —
    the reason "success: true" could previously survive a broken/corrupt
    result: each layer was independently guessing at success from whatever
    fields happened to be present.

    status defaults to status_for_error_code(result.get("error_code")); pass
    it explicitly only for a "warning" result whose error_code is legitimately
    None (a healthy-shaped but non-fatal-limited result, e.g. no memory store
    saved yet).

    include_status_field=False for AddTodoWorkflow/MarkTodoDoneWorkflow ONLY:
    both already have a top-level "status" field meaning the TOUCHED TODO's
    own state ("open"/"done"), pre-dating this contract and depended on by
    existing callers/tests/CLI output — stamping the health-status word under
    the same key would silently corrupt that unrelated, already-public field.
    success/error_code/warnings are still fully stamped either way; a caller
    that wants the health-status word for those two can derive it from
    error_code via status_for_error_code().
    """
    error_code = result.get("error_code")
    resolved_status = status or status_for_error_code(error_code)
    if include_status_field:
        result["status"] = resolved_status
    result["success"] = resolved_status in ("healthy", "warning")
    result.setdefault("warnings", list(warnings or []))
    if warnings:
        result["warnings"] = list(warnings)
    return result


# ---------------------------------------------------------------------------
# Frontmatter parser / writer (no PyYAML)
# ---------------------------------------------------------------------------

def parse_frontmatter(text: str) -> tuple[dict[str, Any], str]:
    """Return (meta, body) from markdown with YAML-like frontmatter.

    Supported value types: null, bool, int, simple list, string.
    """
    if not text.startswith("---"):
        return {}, text
    try:
        end = text.index("---", 3)
    except ValueError:
        return {}, text
    yaml_block = text[3:end].strip()
    body = text[end + 3:].lstrip("\n")
    meta: dict[str, Any] = {}
    for raw_line in yaml_block.splitlines():
        line = raw_line.strip()
        if not line or not line.startswith("#") is False or ":" not in line:
            if ":" not in line:
                continue
        key, _, raw_val = line.partition(":")
        key = key.strip()
        val = raw_val.strip()
        if val in ("null", "~", ""):
            meta[key] = None
        elif val == "true":
            meta[key] = True
        elif val == "false":
            meta[key] = False
        elif re.fullmatch(r"[1-9][0-9]*|0", val):
            meta[key] = int(val)
        elif val.startswith("[") and val.endswith("]"):
            inner = val[1:-1]
            meta[key] = [v.strip().strip("'\"") for v in inner.split(",") if v.strip()]
        else:
            meta[key] = val
    return meta, body


def write_frontmatter(meta: dict[str, Any], body: str) -> str:
    """Serialize meta dict + body into frontmatter markdown."""
    lines = ["---"]
    for k, v in meta.items():
        if v is None:
            lines.append(f"{k}: null")
        elif isinstance(v, bool):
            lines.append(f"{k}: {'true' if v else 'false'}")
        elif isinstance(v, list):
            inner = ", ".join(str(item) for item in v)
            lines.append(f"{k}: [{inner}]")
        else:
            lines.append(f"{k}: {v}")
    lines.append("---")
    return "\n".join(lines) + "\n\n" + body.rstrip("\n") + "\n"


# ---------------------------------------------------------------------------
# .state.json — sequence numbers, never read by Claude
# ---------------------------------------------------------------------------

class MemoryStateCorruptError(Exception):
    """Raised by _read_state when .state.json EXISTS but cannot be parsed as
    a JSON object.

    Deliberately distinct from "file does not exist yet" (a normal, safe
    default for a brand-new store). Previously, a corrupt-but-present file
    silently fell back to {"next_decision_id": 1}, and the very next
    claim_next_id() call would persist that reset counter back to disk —
    risking a duplicate id that collides with an already-existing decision or
    todo. Callers must catch this and refuse to claim/persist a reset counter
    rather than silently trusting the fallback as new source of truth. The
    original corrupt file is left on disk untouched, as the only evidence of
    what went wrong.
    """


def _read_state(skilllayer_dir: Path) -> dict[str, Any]:
    state_file = skilllayer_dir / ".state.json"
    if not state_file.exists():
        return {"next_decision_id": 1}
    try:
        data = json.loads(state_file.read_text(encoding="utf-8"))
    except (json.JSONDecodeError, OSError) as exc:
        raise MemoryStateCorruptError(f".state.json exists but is not valid JSON: {exc}") from exc
    if not isinstance(data, dict):
        raise MemoryStateCorruptError(".state.json exists but does not contain a JSON object.")
    return data


def _write_state(skilllayer_dir: Path, state: dict[str, Any]) -> None:
    atomic_write_json(skilllayer_dir / ".state.json", state)


def claim_next_id(skilllayer_dir: Path, counter_key: str) -> str:
    """Claim and persist the next zero-padded 4-digit id for the given counter.

    Generalized from the original decision-only claim_next_decision_id so
    CrossSessionTodoWorkflow's todo ids can share the same collision-free
    counter mechanism in .state.json (via a separate "next_todo_id" key)
    instead of a second, independently-implemented one.

    The read-modify-write is performed under the whole-store memory_lock, so
    two concurrent processes can never claim the same id. Reentrant: safe to
    call standalone, or nested inside a caller's own already-held
    memory_lock() (e.g. add_todo's larger transaction).

    Raises MemoryStateCorruptError if .state.json exists but is unreadable —
    never silently resets the counter and persists that reset.
    """
    with memory_lock(skilllayer_dir):
        state = _read_state(skilllayer_dir)
        n = int(state.get(counter_key, 1))
        state[counter_key] = n + 1
        _write_state(skilllayer_dir, state)
        return f"{n:04d}"


# ---------------------------------------------------------------------------
# Slug helper
# ---------------------------------------------------------------------------

def _slugify(title: str) -> str:
    """Convert a title to a lowercase hyphenated filename slug."""
    slug = title.lower()
    slug = re.sub(r"[^a-z0-9]+", "-", slug)
    return slug.strip("-")[:60]


# ---------------------------------------------------------------------------
# INDEX.md — regenerated from all three stores after every write
# ---------------------------------------------------------------------------

def extract_section_body(body: str, heading: str) -> str:
    """Extract the text content under a markdown ## heading.

    Public (not module-private) because runner/core.py's
    CompareContextSnapshotsWorkflow reuses it to pull State/Open Questions
    out of two parsed snapshots, rather than re-implementing this parsing.
    """
    heading_pat = re.compile(r"^#{1,6}\s+" + re.escape(heading) + r"\s*$")
    lines = body.splitlines()
    in_section = False
    result: list[str] = []
    for line in lines:
        if heading_pat.match(line):
            in_section = True
            continue
        if in_section:
            if re.match(r"^#{1,6}\s+", line):
                break
            result.append(line)
    return "\n".join(result).strip()


# ---------------------------------------------------------------------------
# NeedsWrap — "you did work, you never saved it"
#
# Automatic, read-only check surfaced in INDEX.md by regenerate_index() and
# recomputed live by rehydrate_context(). Reuses two files that already exist —
# context/latest.md (last save time) and file_watch_snapshot.json (per-file
# mtimes from the LAST WatchFileChanges run). It NEVER triggers a new scan and
# never calls WatchFileChangesWorkflow; it only reads what is already on disk.
# ---------------------------------------------------------------------------

NEEDS_WRAP_SAMPLE_CAP = 5


def _parse_iso(ts: Any) -> datetime | None:
    """Tolerant ISO-8601 parse -> aware UTC datetime, or None.

    Handles both timestamp formats in play without assuming either:
      - latest.md 'created':        '2026-07-07T14:22:05Z'
      - snapshot recorded_at/mtime: '2026-07-07T14:22:05.123456+00:00'
    Python 3.10's datetime.fromisoformat() rejects a trailing 'Z', so it is
    normalized to '+00:00' first. Naive results are assumed UTC.
    """
    if not isinstance(ts, str) or not ts.strip():
        return None
    text = ts.strip()
    if text.endswith("Z"):
        text = text[:-1] + "+00:00"
    try:
        dt = datetime.fromisoformat(text)
    except ValueError:
        return None
    if dt.tzinfo is None:
        dt = dt.replace(tzinfo=timezone.utc)
    return dt.astimezone(timezone.utc)


def _recent_watch_paths(files: dict[str, Any], cap: int) -> list[str]:
    """Return up to `cap` watched paths, most-recently-modified first."""
    _floor = datetime.min.replace(tzinfo=timezone.utc)
    items: list[tuple[str, datetime]] = []
    for rel, info in files.items():
        if not isinstance(info, dict):
            continue
        items.append((rel, _parse_iso(info.get("mtime")) or _floor))
    items.sort(key=lambda pair: (pair[1], pair[0]), reverse=True)
    return [rel for rel, _ in items[:cap]]


def compute_needs_wrap(skilllayer_dir: Path) -> dict[str, Any]:
    """Detect real file changes since the last saved context snapshot.

    Pure read of context/latest.md and file_watch_snapshot.json. Returns a
    structured dict; regenerate_index() renders it into INDEX.md and
    rehydrate_context() recomputes it live. status is one of:
      unknown      — no file-watch snapshot exists yet (cannot tell; not "clean")
      never_saved  — file-watch data exists but no context snapshot ever saved
      stale_watch  — the last file-watch predates the last snapshot
      needs_wrap   — files were modified on disk since the last snapshot
      clean        — nothing changed since the last snapshot (as of last watch)
    """
    result: dict[str, Any] = {
        "status": "unknown",
        "changed_count": 0,
        "last_snapshot": None,
        "last_file_watch": None,
        "changed_sample": [],
    }

    # Last save time (context/latest.md 'created')
    latest = skilllayer_dir / "context" / "latest.md"
    save_iso: str | None = None
    save_dt: datetime | None = None
    if latest.exists():
        try:
            meta, _ = parse_frontmatter(latest.read_text(encoding="utf-8"))
            created = meta.get("created")
            if isinstance(created, str):
                save_iso = created
                save_dt = _parse_iso(created)
        except OSError:
            save_iso, save_dt = None, None
    result["last_snapshot"] = save_iso

    # Last file-watch snapshot (never re-scan — read what WatchFileChanges left)
    snap_path = skilllayer_dir / "file_watch_snapshot.json"
    watch: dict[str, Any] | None = None
    if snap_path.exists():
        try:
            loaded = json.loads(snap_path.read_text(encoding="utf-8"))
            watch = loaded if isinstance(loaded, dict) else None
        except (json.JSONDecodeError, OSError):
            watch = None

    if watch is None:
        result["status"] = "unknown"
        return result

    recorded_iso = watch.get("recorded_at")
    result["last_file_watch"] = recorded_iso if isinstance(recorded_iso, str) else None
    recorded_dt = _parse_iso(recorded_iso)
    files = watch.get("files")
    if not isinstance(files, dict):
        files = {}

    if save_dt is None:
        # File-watch data exists but no context snapshot has ever been saved.
        result["status"] = "never_saved"
        result["changed_count"] = len(files)
        result["changed_sample"] = _recent_watch_paths(files, NEEDS_WRAP_SAMPLE_CAP)
        return result

    if recorded_dt is not None and recorded_dt < save_dt:
        # The watch predates the save; its mtimes cannot speak to post-save work.
        result["status"] = "stale_watch"
        return result

    changed: list[tuple[str, datetime]] = []
    for rel, info in files.items():
        if not isinstance(info, dict):
            continue
        m_dt = _parse_iso(info.get("mtime"))
        if m_dt is not None and m_dt > save_dt:
            changed.append((rel, m_dt))
    changed.sort(key=lambda pair: (pair[1], pair[0]), reverse=True)
    result["changed_count"] = len(changed)
    result["changed_sample"] = [rel for rel, _ in changed[:NEEDS_WRAP_SAMPLE_CAP]]
    result["status"] = "needs_wrap" if changed else "clean"
    return result


def _render_needs_wrap_section(nw: dict[str, Any]) -> str:
    """Render a NeedsWrap result as an INDEX.md section (heading conventions
    match Todos/Decisions: '## <Title> · <Source> — <count/status>')."""
    status = nw.get("status")
    save_date = (nw.get("last_snapshot") or "")[:10]
    watch_at = nw.get("last_file_watch") or "never"
    sample = nw.get("changed_sample") or []
    count = nw.get("changed_count", 0)

    if status == "needs_wrap":
        lines = [
            f"## Unsaved Work · NeedsWrap — {count} files changed since last snapshot",
            f"last snapshot: {save_date or 'never'} · last file-watch: {watch_at}",
            f"{count} file(s) modified on disk after the last saved context snapshot.",
        ]
        if sample:
            lines.append(f"recent: {', '.join(sample)}")
        lines.append("→ Save a context snapshot to consolidate this work.")
        return "\n".join(lines)

    if status == "never_saved":
        lines = [
            "## Unsaved Work · NeedsWrap — no snapshot ever saved",
            f"last file-watch: {watch_at}",
            f"{count} file(s) tracked on disk but no context snapshot has ever been saved.",
        ]
        if sample:
            lines.append(f"recent: {', '.join(sample)}")
        lines.append("→ Save a context snapshot to consolidate this work.")
        return "\n".join(lines)

    if status == "stale_watch":
        return (
            "## Unsaved Work · NeedsWrap — file-watch is stale\n"
            f"last snapshot: {save_date or 'never'} · last file-watch: {watch_at}\n"
            "The last file-watch predates your last snapshot. "
            "Re-run WatchFileChanges to check for newer work."
        )

    if status == "clean":
        return (
            "## Unsaved Work · NeedsWrap — clean\n"
            f"last snapshot: {save_date or 'never'} · last file-watch: {watch_at}\n"
            "No files changed since the last snapshot (as of the last file-watch)."
        )

    # unknown
    return (
        "## Unsaved Work · NeedsWrap — unknown\n"
        "No file-watch data yet. Run WatchFileChanges to enable unsaved-work detection."
    )


def regenerate_index(skilllayer_dir: Path) -> str:
    """Rebuild INDEX.md from context/latest.md, decisions/*.md, preferences.md."""
    sections: list[str] = []

    # --- Context ---
    latest = skilllayer_dir / "context" / "latest.md"
    if latest.exists():
        ctx_meta, ctx_body = parse_frontmatter(latest.read_text(encoding="utf-8"))
        created = str(ctx_meta.get("created", _utc_date()))[:10]
        state_text = extract_section_body(ctx_body, "State")
        state_first = (state_text.splitlines()[0] if state_text else "(no state recorded)").strip()
        oq_text = extract_section_body(ctx_body, "Open Questions")
        oqs = [ln.lstrip("- ").strip() for ln in oq_text.splitlines() if ln.strip().startswith("-")]
        oq_block = "\n".join(f"  - {q}" for q in oqs) if oqs else "  (none)"
        sections.append(
            f"## Context · SaveContextSnapshot\n"
            f"snapshot: context/latest.md · {created}\n"
            f"state: {state_first}\n"
            f"open_questions: {len(oqs)}\n"
            f"{oq_block}"
        )

    # --- Decisions ---
    decisions_dir = skilllayer_dir / "decisions"
    all_files = sorted(decisions_dir.glob("*.md")) if decisions_dir.exists() else []
    total = len(all_files)
    last_three = all_files[-3:]
    d_lines: list[str] = []
    for df in reversed(last_three):
        d_meta, _ = parse_frontmatter(df.read_text(encoding="utf-8"))
        d_id = str(d_meta.get("id", df.stem[:4]))
        raw_stem = df.stem
        title_part = raw_stem[5:].replace("-", " ") if len(raw_stem) > 5 else raw_stem
        d_status = str(d_meta.get("status", "proposed"))
        d_created = str(d_meta.get("created", ""))[:10]
        d_lines.append(f"- {d_id} {title_part} · {d_status} · {d_created}")
    d_block = "\n".join(d_lines) if d_lines else "  (none)"
    sections.append(
        f"## Decisions · TrackDecisionLog — {total} total, last 3\n"
        f"{d_block}\n"
        f"full log: decisions/"
    )

    # --- Preferences ---
    prefs_file = skilllayer_dir / "preferences.md"
    if prefs_file.exists():
        _, prefs_body = parse_frontmatter(prefs_file.read_text(encoding="utf-8"))
        digest_lines: list[str] = []
        current_domain: str | None = None
        added_per_domain: set[str] = set()
        for line in prefs_body.splitlines():
            stripped = line.strip()
            if stripped.startswith("## "):
                current_domain = stripped[3:].strip().lower()
                added_per_domain = set()
            elif stripped.startswith("- ") and current_domain:
                key_val = stripped[2:].strip()
                if current_domain not in added_per_domain:
                    digest_lines.append(f"- {current_domain}: {key_val}")
                    added_per_domain.add(current_domain)
        digest = "\n".join(digest_lines) if digest_lines else "  (none)"
        sections.append(
            f"## Preferences · RememberUserPreferences\n"
            f"{digest}\n"
            f"full: preferences.md"
        )

    # --- Todos ---
    todos_file = skilllayer_dir / TODOS_FILENAME
    if todos_file.exists():
        try:
            todos_data = json.loads(todos_file.read_text(encoding="utf-8"))
            all_todos = todos_data.get("todos", []) if isinstance(todos_data, dict) else []
        except (json.JSONDecodeError, OSError):
            all_todos = []
        open_todos = [t for t in all_todos if isinstance(t, dict) and t.get("status") == "open"]
        # All open todos, not a "last N" digest — unlike Decisions, the whole
        # point is showing everything still outstanding. The cap is a pure
        # runaway guard, not a deliberate truncation.
        shown = open_todos[:TODO_INDEX_DISPLAY_CAP]
        t_lines = [f"- {t['id']} {t['text']}" for t in shown]
        if len(open_todos) > TODO_INDEX_DISPLAY_CAP:
            t_lines.append(f"  ... and {len(open_todos) - TODO_INDEX_DISPLAY_CAP} more open todo(s)")
        t_block = "\n".join(t_lines) if t_lines else "  (none)"
        sections.append(
            f"## Todos · CrossSessionTodo — {len(open_todos)} open\n"
            f"{t_block}\n"
            f"full list: {TODOS_FILENAME}"
        )

    # --- Unsaved work (NeedsWrap) ---
    # Only surface when there is something to reason about (a context snapshot
    # or file-watch data exists), matching how the other sections appear only
    # when their source exists — avoids noise on a brand-new empty store.
    snap_path = skilllayer_dir / "file_watch_snapshot.json"
    if latest.exists() or snap_path.exists():
        sections.append(_render_needs_wrap_section(compute_needs_wrap(skilllayer_dir)))

    meta = {"schema": SCHEMA_VERSION, "updated": _utc_iso()}
    return write_frontmatter(meta, "\n\n".join(sections))


def write_index(skilllayer_dir: Path) -> None:
    """Write the regenerated INDEX.md to disk.

    Locked and atomic. Reentrant: safe standalone, or nested inside a
    caller's larger already-locked transaction (every write workflow calls
    this as its final step) — regenerating and writing the index happens
    under the SAME lock as the rest of that transaction, so INDEX.md is never
    regenerated from a partially-updated store.
    """
    with memory_lock(skilllayer_dir):
        atomic_write_text(skilllayer_dir / "INDEX.md", regenerate_index(skilllayer_dir))


# ---------------------------------------------------------------------------
# SaveContextSnapshot
# ---------------------------------------------------------------------------

def save_context_snapshot(
    skilllayer_dir: Path,
    state: str,
    open_questions: list[str],
) -> dict[str, Any]:
    """Write context/latest.md (latest-wins). Rotate previous to history/.

    The rotate + prune + write + reindex sequence runs as one transaction
    under memory_lock, so two concurrent SaveContextSnapshot calls cannot
    interleave (e.g. both rotating the same latest.md, or one reading a
    half-rotated history/ while pruning)."""
    skilllayer_dir.mkdir(parents=True, exist_ok=True)
    context_dir = skilllayer_dir / "context"
    context_dir.mkdir(exist_ok=True)
    history_dir = context_dir / "history"
    history_dir.mkdir(exist_ok=True)

    latest = context_dir / "latest.md"

    try:
        with memory_lock(skilllayer_dir):
            # Rotate existing latest to history
            if latest.exists():
                ts = _utc_filename_ts()
                history_dest = history_dir / f"{ts}.md"
                latest.rename(history_dest)

            # Prune history beyond HISTORY_KEEP
            history_files = sorted(history_dir.glob("*.md"))
            for old_file in history_files[:-HISTORY_KEEP]:
                old_file.unlink()
            history_count = len(list(history_dir.glob("*.md")))

            # Build new latest.md
            oq_lines = "\n".join(f"- {q}" for q in open_questions) if open_questions else "(none)"
            body = f"## State\n{state}\n\n## Open Questions\n{oq_lines}\n"
            now = _utc_iso()
            meta: dict[str, Any] = {
                "schema": SCHEMA_VERSION,
                "type": "context_snapshot",
                "workflow": "SaveContextSnapshotWorkflow",
                "id": "latest",
                "created": now,
                "updated": now,
            }
            atomic_write_text(latest, write_frontmatter(meta, body))
            write_index(skilllayer_dir)
    except MemoryLockTimeoutError as exc:
        return finalize_memory_result({
            "workflow": "SaveContextSnapshotWorkflow",
            "context_file": None,
            "history_count": None,
            "open_questions": open_questions,
            "error_code": ERROR_MEMORY_LOCK_TIMEOUT,
            "error": str(exc),
            "summary": "No context snapshot saved: could not acquire the memory lock in time.",
        })
    except PermissionError as exc:
        return finalize_memory_result({
            "workflow": "SaveContextSnapshotWorkflow",
            "context_file": None,
            "history_count": None,
            "open_questions": open_questions,
            "error_code": ERROR_MEMORY_PERMISSION_DENIED,
            "error": str(exc),
            "summary": "No context snapshot saved: permission denied writing to .skilllayer/.",
        })
    except OSError as exc:
        return finalize_memory_result({
            "workflow": "SaveContextSnapshotWorkflow",
            "context_file": None,
            "history_count": None,
            "open_questions": open_questions,
            "error_code": ERROR_MEMORY_IO_ERROR,
            "error": str(exc),
            "summary": "No context snapshot saved: an I/O error occurred writing to .skilllayer/.",
        })

    return finalize_memory_result({
        "workflow": "SaveContextSnapshotWorkflow",
        "context_file": str(latest),
        "history_count": history_count,
        "open_questions": open_questions,
        "error_code": None,
        "error": None,
        "summary": f"Context snapshot saved. {len(open_questions)} open question(s). {history_count} history file(s) retained.",
    })


# ---------------------------------------------------------------------------
# TrackDecisionLog
# ---------------------------------------------------------------------------

def track_decision(
    skilllayer_dir: Path,
    title: str,
    context: str,
    decision: str,
    reasoning: str,
    consequences: str,
    status: str = "proposed",
    related_files: list[str] | None = None,
    supersedes: str | None = None,
) -> dict[str, Any]:
    """Append an immutable ADR file to decisions/.

    The full sequence — claiming an id, writing the new file, flipping any
    superseded file's status, and regenerating the index — runs as one
    transaction under memory_lock, so two concurrent TrackDecisionLog calls
    can never claim the same id or interleave a supersession update."""
    if status not in ("proposed", "accepted", "superseded", "deprecated"):
        status = "proposed"

    skilllayer_dir.mkdir(parents=True, exist_ok=True)
    decisions_dir = skilllayer_dir / "decisions"
    decisions_dir.mkdir(exist_ok=True)

    try:
        with memory_lock(skilllayer_dir):
            try:
                decision_id = claim_next_id(skilllayer_dir, "next_decision_id")
            except MemoryStateCorruptError as exc:
                # include_status_field=False: "status" here is the decision's
                # own proposed/accepted/superseded/deprecated state, not the
                # health-status word (same collision as Add/MarkTodoDone).
                return finalize_memory_result(
                    {
                        "workflow": "TrackDecisionLogWorkflow",
                        "decision_id": None,
                        "file": None,
                        "title": title,
                        "status": None,
                        "supersedes": supersedes,
                        "error_code": ERROR_MEMORY_STATE_CORRUPT,
                        "error": str(exc),
                        "summary": "No decision recorded: .state.json exists but is corrupt. Fix or remove it before recording decisions.",
                    },
                    include_status_field=False,
                )

            slug = _slugify(title)
            filename = f"{decision_id}-{slug}.md"
            decision_file = decisions_dir / filename

            now = _utc_iso()
            meta: dict[str, Any] = {
                "schema": SCHEMA_VERSION,
                "type": "decision",
                "workflow": "TrackDecisionLogWorkflow",
                "id": decision_id,
                "status": status,
                "supersedes": supersedes,
                "created": now,
                "updated": now,
            }
            if related_files:
                meta["related_files"] = related_files

            body = (
                f"# {title}\n\n"
                f"## Context\n{context}\n\n"
                f"## Decision\n{decision}\n\n"
                f"## Reasoning\n{reasoning}\n\n"
                f"## Consequences\n{consequences}\n"
            )
            atomic_write_text(decision_file, write_frontmatter(meta, body))

            # If this supersedes an older decision, flip its status
            if supersedes:
                old_files = list(decisions_dir.glob(f"{supersedes}-*.md"))
                for old_file in old_files:
                    old_meta, old_body = parse_frontmatter(old_file.read_text(encoding="utf-8"))
                    old_meta["status"] = "superseded"
                    old_meta["superseded_by"] = decision_id
                    atomic_write_text(old_file, write_frontmatter(old_meta, old_body))

            write_index(skilllayer_dir)
    except MemoryLockTimeoutError as exc:
        return finalize_memory_result(
            {
                "workflow": "TrackDecisionLogWorkflow",
                "decision_id": None,
                "file": None,
                "title": title,
                "status": None,
                "supersedes": supersedes,
                "error_code": ERROR_MEMORY_LOCK_TIMEOUT,
                "error": str(exc),
                "summary": "No decision recorded: could not acquire the memory lock in time.",
            },
            include_status_field=False,
        )
    except PermissionError as exc:
        return finalize_memory_result(
            {
                "workflow": "TrackDecisionLogWorkflow",
                "decision_id": None,
                "file": None,
                "title": title,
                "status": None,
                "supersedes": supersedes,
                "error_code": ERROR_MEMORY_PERMISSION_DENIED,
                "error": str(exc),
                "summary": "No decision recorded: permission denied writing to .skilllayer/.",
            },
            include_status_field=False,
        )
    except OSError as exc:
        return finalize_memory_result(
            {
                "workflow": "TrackDecisionLogWorkflow",
                "decision_id": None,
                "file": None,
                "title": title,
                "status": None,
                "supersedes": supersedes,
                "error_code": ERROR_MEMORY_IO_ERROR,
                "error": str(exc),
                "summary": "No decision recorded: an I/O error occurred writing to .skilllayer/.",
            },
            include_status_field=False,
        )

    return finalize_memory_result(
        {
            "workflow": "TrackDecisionLogWorkflow",
            "decision_id": decision_id,
            "file": str(decision_file),
            "title": title,
            "status": status,
            "supersedes": supersedes,
            "error_code": None,
            "error": None,
            "summary": f"Decision {decision_id} recorded: {title!r} ({status}).",
        },
        include_status_field=False,
    )


# ---------------------------------------------------------------------------
# RememberUserPreferences
# ---------------------------------------------------------------------------

def remember_preferences(
    skilllayer_dir: Path,
    preferences: dict[str, dict[str, str]],
) -> dict[str, Any]:
    """Upsert preferences.md by domain. Last-writer-wins per key.

    The read + merge + write + reindex sequence runs as one transaction
    under memory_lock, so two concurrent RememberUserPreferences calls can
    never lose one call's update to the other's read-modify-write race —
    last-writer-wins is enforced by lock ordering, not by chance timing."""
    skilllayer_dir.mkdir(parents=True, exist_ok=True)
    prefs_file = skilllayer_dir / "preferences.md"

    try:
        with memory_lock(skilllayer_dir):
            # Load existing preferences
            existing: dict[str, dict[str, str]] = {}
            if prefs_file.exists():
                _, body = parse_frontmatter(prefs_file.read_text(encoding="utf-8"))
                current_domain: str | None = None
                for line in body.splitlines():
                    stripped = line.strip()
                    if stripped.startswith("## "):
                        current_domain = stripped[3:].strip().lower()
                        existing.setdefault(current_domain, {})
                    elif stripped.startswith("- ") and current_domain:
                        if ": " in stripped[2:]:
                            k, _, v = stripped[2:].partition(": ")
                            existing[current_domain][k.strip()] = v.strip()

            # Merge (last-writer-wins per key within domain)
            for domain, keys in preferences.items():
                domain_lower = domain.lower()
                existing.setdefault(domain_lower, {})
                existing[domain_lower].update(keys)

            # Serialize preferences.md
            sections_updated = sorted(existing.keys())
            body_parts: list[str] = []
            for domain in sections_updated:
                lines = [f"## {domain}"]
                for k, v in sorted(existing[domain].items()):
                    lines.append(f"- {k}: {v}")
                body_parts.append("\n".join(lines))
            body = "\n\n".join(body_parts) + "\n"

            now = _utc_iso()
            meta: dict[str, Any] = {
                "schema": SCHEMA_VERSION,
                "type": "preferences",
                "workflow": "RememberUserPreferencesWorkflow",
                "id": "preferences",
                "updated": now,
            }
            atomic_write_text(prefs_file, write_frontmatter(meta, body))
            write_index(skilllayer_dir)
    except MemoryLockTimeoutError as exc:
        return finalize_memory_result({
            "workflow": "RememberUserPreferencesWorkflow",
            "preferences_file": None,
            "sections_updated": None,
            "error_code": ERROR_MEMORY_LOCK_TIMEOUT,
            "error": str(exc),
            "summary": "No preferences updated: could not acquire the memory lock in time.",
        })
    except PermissionError as exc:
        return finalize_memory_result({
            "workflow": "RememberUserPreferencesWorkflow",
            "preferences_file": None,
            "sections_updated": None,
            "error_code": ERROR_MEMORY_PERMISSION_DENIED,
            "error": str(exc),
            "summary": "No preferences updated: permission denied writing to .skilllayer/.",
        })
    except OSError as exc:
        return finalize_memory_result({
            "workflow": "RememberUserPreferencesWorkflow",
            "preferences_file": None,
            "sections_updated": None,
            "error_code": ERROR_MEMORY_IO_ERROR,
            "error": str(exc),
            "summary": "No preferences updated: an I/O error occurred writing to .skilllayer/.",
        })

    return finalize_memory_result({
        "workflow": "RememberUserPreferencesWorkflow",
        "preferences_file": str(prefs_file),
        "sections_updated": sections_updated,
        "error_code": None,
        "error": None,
        "summary": f"Preferences updated. Sections: {', '.join(sections_updated)}.",
    })


# ---------------------------------------------------------------------------
# RehydrateContext (read-only)
# ---------------------------------------------------------------------------

def rehydrate_context(
    skilllayer_dir: Path,
    *,
    full_context: bool = False,
    decision_id: str | None = None,
    full_preferences: bool = False,
) -> dict[str, Any]:
    """Read-only. Returns INDEX.md digest plus optional drill-down content.

    A repository with no .skilllayer/ store yet is a valid, healthy EMPTY
    state — nothing has been saved, not a failure — so this reports
    status="warning"/success=true (a usable, if empty, result), never
    status="error"/success=false. error_code stays None: there is nothing
    wrong, just nothing saved yet."""
    index_file = skilllayer_dir / "INDEX.md"
    if not index_file.exists():
        return finalize_memory_result(
            {
                "workflow": "RehydrateContextWorkflow",
                "index": None,
                "context": None,
                "decision": None,
                "preferences": None,
                "error_code": None,
                "summary": "No .skilllayer/ memory store found at this repository root.",
            },
            status="warning",
            warnings=[
                "No .skilllayer/ memory store found yet at this repository root — nothing "
                "has been saved. Save a context snapshot first using the MCP tool "
                "'skilllayer_save_context' (the CLI cannot perform memory write operations)."
            ],
        )

    index_content = index_file.read_text(encoding="utf-8")
    context_content: str | None = None
    decision_content: str | None = None
    preferences_content: str | None = None

    if full_context:
        latest = skilllayer_dir / "context" / "latest.md"
        if latest.exists():
            context_content = latest.read_text(encoding="utf-8")

    if decision_id is not None:
        decisions_dir = skilllayer_dir / "decisions"
        matches = list(decisions_dir.glob(f"{decision_id}-*.md")) if decisions_dir.exists() else []
        if matches:
            decision_content = matches[0].read_text(encoding="utf-8")
        else:
            decision_content = f"(decision {decision_id} not found)"

    if full_preferences:
        prefs_file = skilllayer_dir / "preferences.md"
        if prefs_file.exists():
            preferences_content = prefs_file.read_text(encoding="utf-8")

    has_extras = any(x is not None for x in (context_content, decision_content, preferences_content))
    summary = "Memory rehydrated from INDEX.md."
    if has_extras:
        parts = []
        if context_content:
            parts.append("full context")
        if decision_content:
            parts.append(f"decision {decision_id}")
        if preferences_content:
            parts.append("full preferences")
        summary = f"Memory rehydrated: index + {', '.join(parts)}."

    # Recompute NeedsWrap LIVE rather than trusting the value baked into
    # INDEX.md at the last write — file changes may have happened since the
    # index was last regenerated, and the whole point is to catch exactly that.
    needs_wrap = compute_needs_wrap(skilllayer_dir)

    return finalize_memory_result({
        "workflow": "RehydrateContextWorkflow",
        "index": index_content,
        "context": context_content,
        "decision": decision_content,
        "preferences": preferences_content,
        "needs_wrap": {
            "status": needs_wrap["status"],
            "changed_count": needs_wrap["changed_count"],
            "last_snapshot": needs_wrap["last_snapshot"],
            "last_file_watch": needs_wrap["last_file_watch"],
            "changed_sample": needs_wrap["changed_sample"],
        },
        "error_code": None,
        "summary": summary,
    })


# ---------------------------------------------------------------------------
# CrossSessionTodo
#
# Distinct from SaveContextSnapshot's Open Questions: a todo has a stable id,
# an explicit status, and is added/completed independently of any narrative
# snapshot rewrite. Flat JSON (not markdown+frontmatter) because a todo is
# short structured bookkeeping, not prose — same split as
# file_watch_snapshot.json vs. the decisions/*.md files.
# ---------------------------------------------------------------------------

TODO_TEXT_MAX_LENGTH = 500
TODOS_FILENAME = "todos.json"
TODO_INDEX_DISPLAY_CAP = 20


class TodosStoreCorruptError(Exception):
    """Raised by _read_todos when todos.json EXISTS but cannot be parsed as the
    expected {"todos": [...]} shape.

    Deliberately distinct from "file does not exist yet" (a normal, safe
    default for a brand-new store). Previously, a corrupt-but-present file
    silently fell back to an empty in-memory todos list, and the very next
    add_todo/mark_todo_done write would persist that empty list back to disk —
    permanently wiping every real todo. Callers must catch this and refuse to
    write rather than silently trusting the fallback as new source of truth.
    """


def _read_todos(skilllayer_dir: Path) -> dict[str, Any]:
    todos_file = skilllayer_dir / TODOS_FILENAME
    if not todos_file.exists():
        return {"schema": SCHEMA_VERSION, "next_id": 1, "todos": []}
    try:
        data = json.loads(todos_file.read_text(encoding="utf-8"))
    except (json.JSONDecodeError, OSError) as exc:
        raise TodosStoreCorruptError(f"{TODOS_FILENAME} exists but is not valid JSON: {exc}") from exc
    if not (isinstance(data, dict) and isinstance(data.get("todos"), list)):
        raise TodosStoreCorruptError(f"{TODOS_FILENAME} exists but is not shaped as {{'todos': [...]}}.")
    return data


def _write_todos(skilllayer_dir: Path, data: dict[str, Any]) -> None:
    atomic_write_json(skilllayer_dir / TODOS_FILENAME, data)


def add_todo(skilllayer_dir: Path, text: str) -> dict[str, Any]:
    """Add one todo. Zero LLM calls.

    The read + claim-id + mutate + write + reindex sequence runs as one
    transaction under memory_lock, so two concurrent AddTodo calls can never
    claim the same id or lose one call's todo to the other's write.

    NOTE: this result's top-level "status" field is the ADDED TODO's own
    state ("open"), not the shared health-status word — see
    finalize_memory_result's include_status_field docstring. success/
    error_code/warnings still follow the shared contract."""
    stripped = text.strip()
    if not stripped:
        return finalize_memory_result({
            "workflow": "AddTodoWorkflow",
            "todo_id": None,
            "text": None,
            "status": None,
            "created": None,
            "error_code": "empty_todo_text",
            "error": "Todo text must not be empty.",
            "summary": "No todo added: text was empty.",
        }, include_status_field=False)
    if len(stripped) > TODO_TEXT_MAX_LENGTH:
        return finalize_memory_result({
            "workflow": "AddTodoWorkflow",
            "todo_id": None,
            "text": None,
            "status": None,
            "created": None,
            "error_code": "todo_text_too_long",
            "error": f"Todo text exceeds {TODO_TEXT_MAX_LENGTH} characters ({len(stripped)}). Keep todos short and actionable.",
            "summary": f"No todo added: text exceeds {TODO_TEXT_MAX_LENGTH} characters.",
        }, include_status_field=False)

    skilllayer_dir.mkdir(parents=True, exist_ok=True)

    try:
        with memory_lock(skilllayer_dir):
            # Read (and validate) BEFORE claiming an id, so a corrupt todos.json
            # fails fast without burning a counter slot on a write that never
            # happens.
            try:
                data = _read_todos(skilllayer_dir)
            except TodosStoreCorruptError as exc:
                return finalize_memory_result({
                    "workflow": "AddTodoWorkflow",
                    "todo_id": None,
                    "text": None,
                    "status": None,
                    "created": None,
                    "error_code": ERROR_TODOS_STORE_CORRUPT,
                    "error": str(exc),
                    "summary": "No todo added: todos.json exists but is corrupt. Fix or remove it before adding todos.",
                }, include_status_field=False)

            try:
                todo_id = claim_next_id(skilllayer_dir, "next_todo_id")
            except MemoryStateCorruptError as exc:
                return finalize_memory_result({
                    "workflow": "AddTodoWorkflow",
                    "todo_id": None,
                    "text": None,
                    "status": None,
                    "created": None,
                    "error_code": ERROR_MEMORY_STATE_CORRUPT,
                    "error": str(exc),
                    "summary": "No todo added: .state.json exists but is corrupt. Fix or remove it before adding todos.",
                }, include_status_field=False)
            now = _utc_iso()
            todo = {"id": todo_id, "text": stripped, "status": "open", "created": now, "done_at": None}

            data["todos"].append(todo)
            _write_todos(skilllayer_dir, data)
            write_index(skilllayer_dir)
    except MemoryLockTimeoutError as exc:
        return finalize_memory_result({
            "workflow": "AddTodoWorkflow",
            "todo_id": None,
            "text": None,
            "status": None,
            "created": None,
            "error_code": ERROR_MEMORY_LOCK_TIMEOUT,
            "error": str(exc),
            "summary": "No todo added: could not acquire the memory lock in time.",
        }, include_status_field=False)
    except PermissionError as exc:
        return finalize_memory_result({
            "workflow": "AddTodoWorkflow",
            "todo_id": None,
            "text": None,
            "status": None,
            "created": None,
            "error_code": ERROR_MEMORY_PERMISSION_DENIED,
            "error": str(exc),
            "summary": "No todo added: permission denied writing to .skilllayer/.",
        }, include_status_field=False)
    except OSError as exc:
        return finalize_memory_result({
            "workflow": "AddTodoWorkflow",
            "todo_id": None,
            "text": None,
            "status": None,
            "created": None,
            "error_code": ERROR_MEMORY_IO_ERROR,
            "error": str(exc),
            "summary": "No todo added: an I/O error occurred writing to .skilllayer/.",
        }, include_status_field=False)

    return finalize_memory_result({
        "workflow": "AddTodoWorkflow",
        "todo_id": todo_id,
        "text": stripped,
        "status": "open",
        "created": now,
        "error_code": None,
        "error": None,
        "summary": f"Todo {todo_id} added: {stripped!r}.",
    }, include_status_field=False)


def mark_todo_done(skilllayer_dir: Path, todo_id: str, status: str = "done") -> dict[str, Any]:
    """Set a todo's status. status="done" completes it (stamps done_at);
    status="open" reopens a previously-done todo (clears done_at). Zero LLM
    calls.

    The read + mutate + write + reindex sequence runs as one transaction
    under memory_lock, so two concurrent status updates (including to
    different todos in the same store) cannot interleave and lose one
    update to the other's write.

    NOTE: this result's top-level "status" field is the TOUCHED TODO's own
    state ("open"/"done"), not the shared health-status word — see
    finalize_memory_result's include_status_field docstring. success/
    error_code/warnings still follow the shared contract."""
    if status not in ("open", "done"):
        return finalize_memory_result({
            "workflow": "MarkTodoDoneWorkflow",
            "todo_id": todo_id,
            "status": None,
            "previous_status": None,
            "done_at": None,
            "error_code": "invalid_status",
            "error": f"status must be 'open' or 'done', got {status!r}.",
            "summary": "No change: invalid target status.",
        }, include_status_field=False)

    try:
        with memory_lock(skilllayer_dir):
            try:
                data = _read_todos(skilllayer_dir)
            except TodosStoreCorruptError as exc:
                return finalize_memory_result({
                    "workflow": "MarkTodoDoneWorkflow",
                    "todo_id": todo_id,
                    "status": None,
                    "previous_status": None,
                    "done_at": None,
                    "error_code": ERROR_TODOS_STORE_CORRUPT,
                    "error": str(exc),
                    "summary": "No change: todos.json exists but is corrupt. Fix or remove it before updating todos.",
                }, include_status_field=False)
            target = next((t for t in data["todos"] if t["id"] == todo_id), None)
            if target is None:
                return finalize_memory_result({
                    "workflow": "MarkTodoDoneWorkflow",
                    "todo_id": todo_id,
                    "status": None,
                    "previous_status": None,
                    "done_at": None,
                    "error_code": ERROR_MEMORY_RECORD_NOT_FOUND,
                    "error": f"No todo with id {todo_id!r}.",
                    "summary": f"No change: todo {todo_id!r} not found.",
                }, include_status_field=False)

            previous_status = target["status"]
            target["status"] = status
            target["done_at"] = _utc_iso() if status == "done" else None

            _write_todos(skilllayer_dir, data)
            write_index(skilllayer_dir)
    except MemoryLockTimeoutError as exc:
        return finalize_memory_result({
            "workflow": "MarkTodoDoneWorkflow",
            "todo_id": todo_id,
            "status": None,
            "previous_status": None,
            "done_at": None,
            "error_code": ERROR_MEMORY_LOCK_TIMEOUT,
            "error": str(exc),
            "summary": "No change: could not acquire the memory lock in time.",
        }, include_status_field=False)
    except PermissionError as exc:
        return finalize_memory_result({
            "workflow": "MarkTodoDoneWorkflow",
            "todo_id": todo_id,
            "status": None,
            "previous_status": None,
            "done_at": None,
            "error_code": ERROR_MEMORY_PERMISSION_DENIED,
            "error": str(exc),
            "summary": "No change: permission denied writing to .skilllayer/.",
        }, include_status_field=False)
    except OSError as exc:
        return finalize_memory_result({
            "workflow": "MarkTodoDoneWorkflow",
            "todo_id": todo_id,
            "status": None,
            "previous_status": None,
            "done_at": None,
            "error_code": ERROR_MEMORY_IO_ERROR,
            "error": str(exc),
            "summary": "No change: an I/O error occurred writing to .skilllayer/.",
        }, include_status_field=False)

    return finalize_memory_result({
        "workflow": "MarkTodoDoneWorkflow",
        "todo_id": todo_id,
        "status": status,
        "previous_status": previous_status,
        "done_at": target["done_at"],
        "error_code": None,
        "error": None,
        "summary": f"Todo {todo_id} marked {status}.",
    }, include_status_field=False)


def list_todos(skilllayer_dir: Path, status_filter: str = "open") -> dict[str, Any]:
    """List/filter todos. Read-only. Zero LLM calls.

    Zero matching todos for a valid filter is a HEALTHY empty result
    (error_code stays None), never treated as broken merely because the list
    is empty — same principle SearchDecisionLogWorkflow already applies to
    zero search matches."""
    if status_filter not in ("open", "done", "all"):
        return finalize_memory_result({
            "workflow": "ListTodosWorkflow",
            "filter_status": status_filter,
            "todos": [],
            "open_count": 0,
            "done_count": 0,
            "total_count": 0,
            "error_code": "invalid_status_filter",
            "error": f"status_filter must be 'open', 'done', or 'all', got {status_filter!r}.",
            "summary": "No results: invalid status filter.",
        })

    try:
        data = _read_todos(skilllayer_dir)
    except TodosStoreCorruptError as exc:
        return finalize_memory_result({
            "workflow": "ListTodosWorkflow",
            "filter_status": status_filter,
            "todos": [],
            "open_count": 0,
            "done_count": 0,
            "total_count": 0,
            "error_code": ERROR_TODOS_STORE_CORRUPT,
            "error": str(exc),
            "summary": "No results: todos.json exists but is corrupt.",
        })
    all_todos = data["todos"]
    open_count = sum(1 for t in all_todos if t["status"] == "open")
    done_count = sum(1 for t in all_todos if t["status"] == "done")
    filtered = all_todos if status_filter == "all" else [t for t in all_todos if t["status"] == status_filter]

    return finalize_memory_result({
        "workflow": "ListTodosWorkflow",
        "filter_status": status_filter,
        "todos": filtered,
        "open_count": open_count,
        "done_count": done_count,
        "total_count": len(all_todos),
        "error_code": None,
        "error": None,
        "summary": f"{open_count} open todo(s), {done_count} done.",
    })


# ---------------------------------------------------------------------------
# ValidateMemoryWorkflow — standalone, on-demand, read-only integrity check
#
# Unlike NeedsWrap, this is NOT wired into regenerate_index()/rehydrate_context:
# it reads and fully parses every decisions/*.md file, todos.json, and
# preferences.md and walks the supersession graph — an O(N) cost over the
# whole store, not appropriate to pay on every single memory write. It is a
# deliberate, standalone diagnostic: call it when you want to know whether the
# store is internally consistent, not automatically on every write.
#
# Read-only: never writes .state.json, INDEX.md, or any memory file. Never
# raises — a missing/corrupt file is reported as a finding, not an exception.
# ---------------------------------------------------------------------------

CHECK_SEVERITY: dict[str, str] = {
    "index_freshness": "warning",
    "context_frontmatter_schema": "broken",
    "context_missing_sections": "broken",
    "decision_frontmatter_schema": "broken",
    "decision_status_invalid": "broken",
    "decision_filename_id_mismatch": "broken",
    "decision_duplicate_id": "broken",
    "decision_supersedes_dangling": "broken",
    "decision_superseded_by_dangling": "broken",
    "decision_status_superseded_by_mismatch": "broken",
    "decision_supersession_cycle": "broken",
    "preferences_frontmatter_schema": "broken",
    "preferences_unparseable_line": "warning",
    "todos_file_shape": "broken",
    "todos_entry_missing_fields": "broken",
    "todos_status_invalid": "broken",
    "todos_done_at_mismatch": "warning",
    "todos_duplicate_id": "broken",
    "decision_counter_behind": "broken",
    "todo_counter_behind": "broken",
}

_DECISION_REQUIRED_FIELDS = ("schema", "id", "status", "created")
_CONTEXT_REQUIRED_FIELDS = ("schema", "type", "id", "created")
_PREFERENCES_REQUIRED_FIELDS = ("schema", "type", "id")
_TODO_REQUIRED_FIELDS = ("id", "text", "status", "created", "done_at")
_DECISION_STATUSES = ("proposed", "accepted", "superseded", "deprecated")
_DECISION_FILENAME_RE = re.compile(r"^(\d{4})-")


def _finding(check: str, file: str | None, message: str, suggested_fix: str) -> dict[str, Any]:
    return {
        "check": check,
        "severity": CHECK_SEVERITY[check],
        "file": file,
        "message": message,
        "suggested_fix": suggested_fix,
    }


def _try_read_json(path: Path) -> Any:
    """Lenient JSON read. Returns None on any missing/unreadable/invalid input.
    Never raises — used only by the validator, which must never crash."""
    if not path.exists():
        return None
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except (json.JSONDecodeError, OSError):
        return None


def _has_heading(body: str, heading: str) -> bool:
    pat = re.compile(r"^#{1,6}\s+" + re.escape(heading) + r"\s*$", re.MULTILINE)
    return bool(pat.search(body))


def _max_numeric_id(ids: Any) -> int:
    best = 0
    for i in ids:
        try:
            best = max(best, int(str(i)))
        except (TypeError, ValueError):
            continue
    return best


def _load_decision_records(skilllayer_dir: Path) -> list[dict[str, Any]]:
    """Read every decisions/*.md file leniently. Never raises."""
    decisions_dir = skilllayer_dir / "decisions"
    records: list[dict[str, Any]] = []
    if not decisions_dir.exists():
        return records
    for path in sorted(decisions_dir.glob("*.md")):
        try:
            raw = path.read_text(encoding="utf-8")
        except OSError:
            continue
        meta, body = parse_frontmatter(raw)
        records.append({"filename": path.name, "meta": meta, "body": body})
    return records


def _decision_effective_id(record: dict[str, Any]) -> str | None:
    """The id used for chain lookups: prefer frontmatter id, else filename prefix."""
    meta_id = record["meta"].get("id")
    if meta_id is not None:
        return str(meta_id)
    m = _DECISION_FILENAME_RE.match(record["filename"])
    return m.group(1) if m else None


def _index_decisions_by_id(
    records: list[dict[str, Any]],
) -> tuple[dict[str, list[dict[str, Any]]], dict[str, list[str]]]:
    by_id: dict[str, list[dict[str, Any]]] = {}
    for r in records:
        eff_id = _decision_effective_id(r)
        if eff_id is None:
            continue
        by_id.setdefault(eff_id, []).append(r)
    duplicates = {k: [r["filename"] for r in v] for k, v in by_id.items() if len(v) > 1}
    return by_id, duplicates


def _find_supersession_cycles(edges: dict[str, str | None]) -> list[list[str]]:
    """Detect cycles (including a direct self-reference) in the supersedes
    graph. Dangling targets (not a key in `edges`) are dead ends, not cycle
    participants — those are reported separately as dangling references."""
    WHITE, GRAY, BLACK = 0, 1, 2
    color = {k: WHITE for k in edges}
    cycles: list[list[str]] = []
    reported: set[frozenset] = set()

    def visit(node: str, path: list[str]) -> None:
        color[node] = GRAY
        path.append(node)
        target = edges.get(node)
        if target is not None and target in edges:
            if color[target] == GRAY:
                idx = path.index(target)
                cycle = path[idx:] + [target]
                key = frozenset(cycle[:-1])
                if key not in reported:
                    cycles.append(cycle)
                    reported.add(key)
            elif color[target] == WHITE:
                visit(target, path)
        path.pop()
        color[node] = BLACK

    for node in list(edges):
        if color[node] == WHITE:
            visit(node, [])
    return cycles


# --- Group A: INDEX freshness ------------------------------------------------

def _check_index_freshness(skilllayer_dir: Path, index_text: str | None) -> list[dict[str, Any]]:
    if index_text is None:
        return [_finding(
            "index_freshness", "INDEX.md",
            "INDEX.md does not exist yet.",
            "Run any memory write workflow (SaveContextSnapshot, TrackDecisionLog, "
            "RememberUserPreferences, AddTodo) to generate it.",
        )]
    fresh_meta, fresh_body = parse_frontmatter(regenerate_index(skilllayer_dir))
    disk_meta, disk_body = parse_frontmatter(index_text)
    fresh_meta.pop("updated", None)
    disk_meta.pop("updated", None)
    if fresh_meta != disk_meta or fresh_body != disk_body:
        return [_finding(
            "index_freshness", "INDEX.md",
            "INDEX.md content does not match a freshly regenerated index — it is stale "
            "relative to context/latest.md, decisions/*.md, preferences.md, and todos.json.",
            "Call any memory write workflow, or regenerate_index()+write_index(), to refresh it.",
        )]
    return []


# --- Group C: context/latest.md ---------------------------------------------

def _check_context_frontmatter(latest_exists: bool, ctx_meta: dict[str, Any]) -> list[dict[str, Any]]:
    if not latest_exists:
        return []
    missing = [k for k in _CONTEXT_REQUIRED_FIELDS if ctx_meta.get(k) is None]
    if not missing:
        return []
    if not ctx_meta:
        msg = "context/latest.md has missing or unparseable frontmatter."
    else:
        msg = f"context/latest.md frontmatter is missing required field(s): {', '.join(missing)}."
    return [_finding("context_frontmatter_schema", "context/latest.md", msg,
                      "Rewrite the frontmatter block with schema/type/id/created, or re-save via SaveContextSnapshot.")]


def _check_context_sections(latest_exists: bool, ctx_body: str) -> list[dict[str, Any]]:
    if not latest_exists:
        return []
    missing = [h for h in ("State", "Open Questions") if not _has_heading(ctx_body, h)]
    if not missing:
        return []
    return [_finding(
        "context_missing_sections", "context/latest.md",
        f"context/latest.md body is missing section(s): {', '.join('## ' + h for h in missing)}.",
        "Re-save the context snapshot via SaveContextSnapshot so both sections are written.",
    )]


# --- Group C: decisions/*.md -------------------------------------------------

def _check_decision_frontmatter(records: list[dict[str, Any]]) -> list[dict[str, Any]]:
    findings = []
    for r in records:
        missing = [k for k in _DECISION_REQUIRED_FIELDS if r["meta"].get(k) is None]
        if not missing:
            continue
        if not r["meta"]:
            msg = f"{r['filename']} has missing or unparseable frontmatter."
        else:
            msg = f"{r['filename']} frontmatter is missing required field(s): {', '.join(missing)}."
        findings.append(_finding("decision_frontmatter_schema", f"decisions/{r['filename']}", msg,
                                  "Rewrite the frontmatter block with schema/id/status/created."))
    return findings


def _check_decision_status(records: list[dict[str, Any]]) -> list[dict[str, Any]]:
    findings = []
    for r in records:
        status = r["meta"].get("status")
        if status is not None and status not in _DECISION_STATUSES:
            findings.append(_finding(
                "decision_status_invalid", f"decisions/{r['filename']}",
                f"status {status!r} is not one of {_DECISION_STATUSES}.",
                "Correct the status field to one of proposed/accepted/superseded/deprecated.",
            ))
    return findings


def _check_decision_filename(records: list[dict[str, Any]]) -> list[dict[str, Any]]:
    findings = []
    for r in records:
        m = _DECISION_FILENAME_RE.match(r["filename"])
        if not m:
            findings.append(_finding(
                "decision_filename_id_mismatch", f"decisions/{r['filename']}",
                f"{r['filename']} does not match the expected '{{4-digit-id}}-{{slug}}.md' pattern.",
                "Rename the file to match {id}-{slug}.md, or confirm it belongs in decisions/.",
            ))
            continue
        meta_id = r["meta"].get("id")
        if meta_id is not None and str(meta_id) != m.group(1):
            findings.append(_finding(
                "decision_filename_id_mismatch", f"decisions/{r['filename']}",
                f"filename id {m.group(1)!r} disagrees with frontmatter id {meta_id!r}.",
                "Correct whichever of the filename or frontmatter id is wrong.",
            ))
    return findings


def _check_decision_duplicates(duplicates: dict[str, list[str]]) -> list[dict[str, Any]]:
    findings = []
    for dec_id, filenames in sorted(duplicates.items()):
        findings.append(_finding(
            "decision_duplicate_id", "decisions/",
            f"decision id {dec_id!r} is used by multiple files: {', '.join(filenames)}.",
            "Renumber one of the colliding decisions to a unique id (this can happen if "
            ".state.json's next_decision_id counter was reset or edited).",
        ))
    return findings


def _check_decision_supersedes_dangling(
    records: list[dict[str, Any]], by_id: dict[str, list[dict[str, Any]]]
) -> list[dict[str, Any]]:
    findings = []
    for r in records:
        target = r["meta"].get("supersedes")
        if target and str(target) not in by_id:
            findings.append(_finding(
                "decision_supersedes_dangling", f"decisions/{r['filename']}",
                f"supersedes {target!r}, but no decision with that id exists.",
                "Confirm the target id wasn't deleted/renamed; correct or clear the supersedes field.",
            ))
    return findings


def _check_decision_superseded_by_dangling(
    records: list[dict[str, Any]], by_id: dict[str, list[dict[str, Any]]]
) -> list[dict[str, Any]]:
    findings = []
    for r in records:
        target = r["meta"].get("superseded_by")
        if target and str(target) not in by_id:
            findings.append(_finding(
                "decision_superseded_by_dangling", f"decisions/{r['filename']}",
                f"superseded_by {target!r}, but no decision with that id exists.",
                "Confirm the target id wasn't deleted/renamed; correct or clear the superseded_by field.",
            ))
    return findings


def _check_decision_status_consistency(records: list[dict[str, Any]]) -> list[dict[str, Any]]:
    findings = []
    for r in records:
        status = r["meta"].get("status")
        superseded_by = r["meta"].get("superseded_by")
        if status == "superseded" and not superseded_by:
            findings.append(_finding(
                "decision_status_superseded_by_mismatch", f"decisions/{r['filename']}",
                "status is 'superseded' but superseded_by is not set.",
                "Set superseded_by to the id that supersedes this decision, or correct the status.",
            ))
        elif status != "superseded" and superseded_by:
            findings.append(_finding(
                "decision_status_superseded_by_mismatch", f"decisions/{r['filename']}",
                f"superseded_by={superseded_by!r} is set but status is {status!r}, not 'superseded'.",
                "Set status to 'superseded', or clear the superseded_by field.",
            ))
    return findings


def _check_decision_cycles(by_id: dict[str, list[dict[str, Any]]]) -> list[dict[str, Any]]:
    edges: dict[str, str | None] = {}
    for dec_id, recs in by_id.items():
        target = recs[0]["meta"].get("supersedes")
        edges[dec_id] = str(target) if target else None
    cycles = _find_supersession_cycles(edges)
    return [
        _finding(
            "decision_supersession_cycle", "decisions/",
            f"supersession cycle detected: {' -> '.join(cycle)}.",
            "Manually break the cycle by correcting one decision's supersedes field.",
        )
        for cycle in cycles
    ]


# --- Group C: preferences.md -------------------------------------------------

def _check_preferences_frontmatter(prefs_exists: bool, prefs_meta: dict[str, Any]) -> list[dict[str, Any]]:
    if not prefs_exists:
        return []
    missing = [k for k in _PREFERENCES_REQUIRED_FIELDS if prefs_meta.get(k) is None]
    if not missing:
        return []
    if not prefs_meta:
        msg = "preferences.md has missing or unparseable frontmatter."
    else:
        msg = f"preferences.md frontmatter is missing required field(s): {', '.join(missing)}."
    return [_finding("preferences_frontmatter_schema", "preferences.md", msg,
                      "Rewrite the frontmatter block with schema/type/id, or re-save via RememberUserPreferences.")]


def _check_preferences_lines(prefs_exists: bool, prefs_body: str) -> list[dict[str, Any]]:
    if not prefs_exists:
        return []
    findings = []
    current_domain: str | None = None
    for i, line in enumerate(prefs_body.splitlines(), start=1):
        stripped = line.strip()
        if not stripped:
            continue
        if stripped.startswith("## "):
            current_domain = stripped[3:].strip()
            continue
        if stripped.startswith("- ") and current_domain and ": " in stripped[2:]:
            continue
        findings.append(_finding(
            "preferences_unparseable_line", "preferences.md",
            f"line {i} does not match the expected '## domain' or '- key: value' shape "
            f"and will be silently dropped on the next write: {stripped!r}",
            "Rewrite the line as '- key: value' under a '## domain' heading, or remove it.",
        ))
    return findings


# --- Group C: todos.json ------------------------------------------------------

def _check_todos_shape(todos_exists: bool, todos_shape_ok: bool) -> list[dict[str, Any]]:
    if todos_exists and not todos_shape_ok:
        return [_finding(
            "todos_file_shape", TODOS_FILENAME,
            f"{TODOS_FILENAME} exists but is not valid JSON, or is not shaped as {{'todos': [...]}}.",
            "Fix or remove the file to resume normal todo writes. The next add_todo/"
            "mark_todo_done call will correctly refuse to write over it rather than "
            "silently discarding its contents.",
        )]
    return []


def _check_todos_entry_fields(todos_shape_ok: bool, todos_list: list[Any]) -> list[dict[str, Any]]:
    if not todos_shape_ok:
        return []
    findings = []
    for i, t in enumerate(todos_list):
        if not isinstance(t, dict):
            findings.append(_finding("todos_entry_missing_fields", TODOS_FILENAME,
                                      f"todos[{i}] is not an object.",
                                      "Remove or repair the malformed entry."))
            continue
        missing = [k for k in _TODO_REQUIRED_FIELDS if k not in t]
        if missing:
            tid = t.get("id", f"index {i}")
            findings.append(_finding(
                "todos_entry_missing_fields", TODOS_FILENAME,
                f"todo {tid!r} is missing required field(s): {', '.join(missing)}.",
                "Add the missing field(s), matching the shape written by AddTodoWorkflow.",
            ))
    return findings


def _check_todos_status(todos_shape_ok: bool, todos_list: list[Any]) -> list[dict[str, Any]]:
    if not todos_shape_ok:
        return []
    findings = []
    for t in todos_list:
        if not isinstance(t, dict):
            continue
        status = t.get("status")
        if "status" in t and status not in ("open", "done"):
            findings.append(_finding(
                "todos_status_invalid", TODOS_FILENAME,
                f"todo {t.get('id')!r} has status {status!r}, not 'open' or 'done'.",
                "Correct the status field to 'open' or 'done'.",
            ))
    return findings


def _check_todos_done_at(todos_shape_ok: bool, todos_list: list[Any]) -> list[dict[str, Any]]:
    if not todos_shape_ok:
        return []
    findings = []
    for t in todos_list:
        if not isinstance(t, dict) or "status" not in t or "done_at" not in t:
            continue
        status, done_at = t.get("status"), t.get("done_at")
        if status == "done" and not done_at:
            findings.append(_finding("todos_done_at_mismatch", TODOS_FILENAME,
                                      f"todo {t.get('id')!r} has status 'done' but done_at is not set.",
                                      "Set done_at, or reopen the todo via MarkTodoDone(status='open')."))
        elif status == "open" and done_at:
            findings.append(_finding("todos_done_at_mismatch", TODOS_FILENAME,
                                      f"todo {t.get('id')!r} has status 'open' but done_at is set to {done_at!r}.",
                                      "Clear done_at, or mark the todo done via MarkTodoDone(status='done')."))
    return findings


def _check_todos_duplicates(todos_shape_ok: bool, todos_list: list[Any]) -> list[dict[str, Any]]:
    if not todos_shape_ok:
        return []
    ids: dict[str, int] = {}
    for t in todos_list:
        if isinstance(t, dict) and "id" in t:
            ids[str(t["id"])] = ids.get(str(t["id"]), 0) + 1
    return [
        _finding("todos_duplicate_id", TODOS_FILENAME,
                 f"todo id {tid!r} is used by {count} entries.",
                 "Renumber the colliding todos to unique ids (this can happen if .state.json's "
                 "next_todo_id counter was reset or edited).")
        for tid, count in sorted(ids.items()) if count > 1
    ]


# --- Group D: ID counter drift ------------------------------------------------

def _check_decision_counter(state_data: dict[str, Any], by_id: dict[str, list[dict[str, Any]]]) -> list[dict[str, Any]]:
    if not by_id:
        return []
    raw = state_data.get("next_decision_id", 1)
    try:
        next_id = int(raw)
    except (TypeError, ValueError):
        return [_finding("decision_counter_behind", ".state.json",
                         f"next_decision_id is not a valid integer: {raw!r}.",
                         "Repair .state.json's next_decision_id to an integer greater than the highest existing decision id.")]
    max_existing = _max_numeric_id(by_id.keys())
    if next_id <= max_existing:
        return [_finding(
            "decision_counter_behind", ".state.json",
            f"next_decision_id={next_id} is <= the highest existing decision id ({max_existing:04d}); "
            "the next TrackDecisionLog call will mint a duplicate id.",
            "Set .state.json's next_decision_id to at least one greater than the highest existing decision id.",
        )]
    return []


def _check_todo_counter(state_data: dict[str, Any], todos_shape_ok: bool, todos_list: list[Any]) -> list[dict[str, Any]]:
    if not todos_shape_ok:
        return []
    ids = [t["id"] for t in todos_list if isinstance(t, dict) and "id" in t]
    if not ids:
        return []
    raw = state_data.get("next_todo_id", 1)
    try:
        next_id = int(raw)
    except (TypeError, ValueError):
        return [_finding("todo_counter_behind", ".state.json",
                         f"next_todo_id is not a valid integer: {raw!r}.",
                         "Repair .state.json's next_todo_id to an integer greater than the highest existing todo id.")]
    max_existing = _max_numeric_id(ids)
    if next_id <= max_existing:
        return [_finding(
            "todo_counter_behind", ".state.json",
            f"next_todo_id={next_id} is <= the highest existing todo id ({max_existing:04d}); "
            "the next AddTodo call will mint a duplicate id.",
            "Set .state.json's next_todo_id to at least one greater than the highest existing todo id.",
        )]
    return []


def validate_memory_store(skilllayer_dir: Path) -> dict[str, Any]:
    """Check the .skilllayer/ memory store for internal consistency.

    Standalone, on-demand, read-only. Never writes anything and never raises —
    a missing or corrupt file is reported as a finding, not an exception.
    Returns store_exists: False (zero checks run) if skilllayer_dir itself
    does not exist yet.
    """
    checked_at = _utc_iso()
    if not skilllayer_dir.exists():
        # No store yet is a valid, healthy-adjacent EMPTY state (nothing has
        # been saved), never "broken" — same treatment as
        # RehydrateContextWorkflow's identical condition.
        return finalize_memory_result(
            {
                "workflow": "ValidateMemoryWorkflow",
                "store_exists": False,
                "checked_at": checked_at,
                "summary": {"checks_run": 0, "checks_passed": 0, "warnings_count": 0, "broken_count": 0},
                "findings": [],
                "error_code": None,
            },
            status="warning",
            warnings=["No .skilllayer/ memory store found yet at this repository root — nothing to validate."],
        )

    # --- LoadMemoryStore ---
    index_path = skilllayer_dir / "INDEX.md"
    index_text = index_path.read_text(encoding="utf-8") if index_path.exists() else None

    latest_path = skilllayer_dir / "context" / "latest.md"
    latest_exists = latest_path.exists()
    ctx_meta, ctx_body = ({}, "")
    if latest_exists:
        ctx_meta, ctx_body = parse_frontmatter(latest_path.read_text(encoding="utf-8"))

    decision_records = _load_decision_records(skilllayer_dir)
    by_id, duplicate_decision_ids = _index_decisions_by_id(decision_records)

    prefs_path = skilllayer_dir / "preferences.md"
    prefs_exists = prefs_path.exists()
    prefs_meta, prefs_body = ({}, "")
    if prefs_exists:
        prefs_meta, prefs_body = parse_frontmatter(prefs_path.read_text(encoding="utf-8"))

    todos_path = skilllayer_dir / TODOS_FILENAME
    todos_exists = todos_path.exists()
    todos_raw = _try_read_json(todos_path)
    todos_shape_ok = isinstance(todos_raw, dict) and isinstance(todos_raw.get("todos"), list)
    todos_list: list[Any] = todos_raw["todos"] if todos_shape_ok else []

    state_raw = _try_read_json(skilllayer_dir / ".state.json")
    state_data: dict[str, Any] = state_raw if isinstance(state_raw, dict) else {}

    # --- CheckIndexFreshness / CheckFrontmatterSchemas / CheckDecisionChainIntegrity / CheckIdCounters ---
    findings_by_check: dict[str, list[dict[str, Any]]] = {
        "index_freshness": _check_index_freshness(skilllayer_dir, index_text),
        "context_frontmatter_schema": _check_context_frontmatter(latest_exists, ctx_meta),
        "context_missing_sections": _check_context_sections(latest_exists, ctx_body),
        "decision_frontmatter_schema": _check_decision_frontmatter(decision_records),
        "decision_status_invalid": _check_decision_status(decision_records),
        "decision_filename_id_mismatch": _check_decision_filename(decision_records),
        "decision_duplicate_id": _check_decision_duplicates(duplicate_decision_ids),
        "decision_supersedes_dangling": _check_decision_supersedes_dangling(decision_records, by_id),
        "decision_superseded_by_dangling": _check_decision_superseded_by_dangling(decision_records, by_id),
        "decision_status_superseded_by_mismatch": _check_decision_status_consistency(decision_records),
        "decision_supersession_cycle": _check_decision_cycles(by_id),
        "preferences_frontmatter_schema": _check_preferences_frontmatter(prefs_exists, prefs_meta),
        "preferences_unparseable_line": _check_preferences_lines(prefs_exists, prefs_body),
        "todos_file_shape": _check_todos_shape(todos_exists, todos_shape_ok),
        "todos_entry_missing_fields": _check_todos_entry_fields(todos_shape_ok, todos_list),
        "todos_status_invalid": _check_todos_status(todos_shape_ok, todos_list),
        "todos_done_at_mismatch": _check_todos_done_at(todos_shape_ok, todos_list),
        "todos_duplicate_id": _check_todos_duplicates(todos_shape_ok, todos_list),
        "decision_counter_behind": _check_decision_counter(state_data, by_id),
        "todo_counter_behind": _check_todo_counter(state_data, todos_shape_ok, todos_list),
    }

    # --- BuildIntegrityReport ---
    findings: list[dict[str, Any]] = []
    checks_passed = warnings_count = broken_count = 0
    for name, severity in CHECK_SEVERITY.items():
        items = findings_by_check[name]
        if not items:
            checks_passed += 1
        elif severity == "broken":
            broken_count += 1
        else:
            warnings_count += 1
        findings.extend(items)

    # status is the single authoritative verdict for the whole store:
    #   any broken finding -> "broken" (data integrity invalid, success=false)
    #   only warning findings -> "warning" (usable, but flagged, success=true)
    #   zero findings -> "healthy" (success=true)
    if broken_count > 0:
        result_status = "broken"
        error_code: str | None = ERROR_MEMORY_INTEGRITY_BROKEN
    else:
        result_status = "warning" if warnings_count > 0 else "healthy"
        error_code = None

    warning_messages = [f["message"] for f in findings if f["severity"] == "warning"]

    return finalize_memory_result(
        {
            "workflow": "ValidateMemoryWorkflow",
            "store_exists": True,
            "checked_at": checked_at,
            "summary": {
                "checks_run": len(CHECK_SEVERITY),
                "checks_passed": checks_passed,
                "warnings_count": warnings_count,
                "broken_count": broken_count,
            },
            "findings": findings,
            "error_code": error_code,
        },
        status=result_status,
        warnings=warning_messages,
    )
