"""SkillLayer .skilllayer/ persistence infrastructure.

Storage root: <repo>/.skilllayer/
Source of truth: markdown + YAML-like frontmatter (schema: 1)
No PyYAML dependency — minimal key:value parser.
Zero LLM calls in all read and write paths.

Directory layout:
  .skilllayer/
    INDEX.md            — digest, regenerated by every write workflow
    context/
      latest.md         — SaveContextSnapshot (latest-wins, gitignored)
      history/          — rotated snapshots, keep last HISTORY_KEEP
    decisions/
      0001-slug.md      — TrackDecisionLog (append-only, immutable)
    preferences.md      — RememberUserPreferences (upsert per section)
    .state.json         — sequence bookkeeping only, never read by Claude
"""
from __future__ import annotations

import json
import re
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

SCHEMA_VERSION = 1
HISTORY_KEEP = 5


# ---------------------------------------------------------------------------
# Timestamps
# ---------------------------------------------------------------------------

def _utc_iso() -> str:
    """ISO-8601 timestamp for frontmatter fields."""
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def _utc_date() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%d")


def _utc_filename_ts() -> str:
    """Compact timestamp safe for filenames."""
    return datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")


# ---------------------------------------------------------------------------
# Frontmatter parser / writer (no PyYAML)
# ---------------------------------------------------------------------------

def parse_frontmatter(text: str) -> tuple[dict[str, Any], str]:
    """Return (meta, body) from markdown with YAML-like frontmatter.

    Supported value types: null, bool, int, simple list, string.
    """
    if not text.startswith("---"):
        return {}, text
    try:
        end = text.index("---", 3)
    except ValueError:
        return {}, text
    yaml_block = text[3:end].strip()
    body = text[end + 3:].lstrip("\n")
    meta: dict[str, Any] = {}
    for raw_line in yaml_block.splitlines():
        line = raw_line.strip()
        if not line or not line.startswith("#") is False or ":" not in line:
            if ":" not in line:
                continue
        key, _, raw_val = line.partition(":")
        key = key.strip()
        val = raw_val.strip()
        if val in ("null", "~", ""):
            meta[key] = None
        elif val == "true":
            meta[key] = True
        elif val == "false":
            meta[key] = False
        elif re.fullmatch(r"[1-9][0-9]*|0", val):
            meta[key] = int(val)
        elif val.startswith("[") and val.endswith("]"):
            inner = val[1:-1]
            meta[key] = [v.strip().strip("'\"") for v in inner.split(",") if v.strip()]
        else:
            meta[key] = val
    return meta, body


def write_frontmatter(meta: dict[str, Any], body: str) -> str:
    """Serialize meta dict + body into frontmatter markdown."""
    lines = ["---"]
    for k, v in meta.items():
        if v is None:
            lines.append(f"{k}: null")
        elif isinstance(v, bool):
            lines.append(f"{k}: {'true' if v else 'false'}")
        elif isinstance(v, list):
            inner = ", ".join(str(item) for item in v)
            lines.append(f"{k}: [{inner}]")
        else:
            lines.append(f"{k}: {v}")
    lines.append("---")
    return "\n".join(lines) + "\n\n" + body.rstrip("\n") + "\n"


# ---------------------------------------------------------------------------
# .state.json — sequence numbers, never read by Claude
# ---------------------------------------------------------------------------

def _read_state(skilllayer_dir: Path) -> dict[str, Any]:
    state_file = skilllayer_dir / ".state.json"
    if state_file.exists():
        try:
            return json.loads(state_file.read_text(encoding="utf-8"))
        except (json.JSONDecodeError, OSError):
            pass
    return {"next_decision_id": 1}


def _write_state(skilllayer_dir: Path, state: dict[str, Any]) -> None:
    state_file = skilllayer_dir / ".state.json"
    state_file.write_text(json.dumps(state, indent=2), encoding="utf-8")


def claim_next_decision_id(skilllayer_dir: Path) -> str:
    """Claim and persist the next zero-padded 4-digit decision id."""
    state = _read_state(skilllayer_dir)
    n = int(state.get("next_decision_id", 1))
    state["next_decision_id"] = n + 1
    _write_state(skilllayer_dir, state)
    return f"{n:04d}"


# ---------------------------------------------------------------------------
# Slug helper
# ---------------------------------------------------------------------------

def _slugify(title: str) -> str:
    """Convert a title to a lowercase hyphenated filename slug."""
    slug = title.lower()
    slug = re.sub(r"[^a-z0-9]+", "-", slug)
    return slug.strip("-")[:60]


# ---------------------------------------------------------------------------
# INDEX.md — regenerated from all three stores after every write
# ---------------------------------------------------------------------------

def _extract_section_body(body: str, heading: str) -> str:
    """Extract the text content under a markdown ## heading."""
    heading_pat = re.compile(r"^#{1,6}\s+" + re.escape(heading) + r"\s*$")
    lines = body.splitlines()
    in_section = False
    result: list[str] = []
    for line in lines:
        if heading_pat.match(line):
            in_section = True
            continue
        if in_section:
            if re.match(r"^#{1,6}\s+", line):
                break
            result.append(line)
    return "\n".join(result).strip()


def regenerate_index(skilllayer_dir: Path) -> str:
    """Rebuild INDEX.md from context/latest.md, decisions/*.md, preferences.md."""
    sections: list[str] = []

    # --- Context ---
    latest = skilllayer_dir / "context" / "latest.md"
    if latest.exists():
        ctx_meta, ctx_body = parse_frontmatter(latest.read_text(encoding="utf-8"))
        created = str(ctx_meta.get("created", _utc_date()))[:10]
        state_text = _extract_section_body(ctx_body, "State")
        state_first = (state_text.splitlines()[0] if state_text else "(no state recorded)").strip()
        oq_text = _extract_section_body(ctx_body, "Open Questions")
        oqs = [ln.lstrip("- ").strip() for ln in oq_text.splitlines() if ln.strip().startswith("-")]
        oq_block = "\n".join(f"  - {q}" for q in oqs) if oqs else "  (none)"
        sections.append(
            f"## Context · SaveContextSnapshot\n"
            f"snapshot: context/latest.md · {created}\n"
            f"state: {state_first}\n"
            f"open_questions: {len(oqs)}\n"
            f"{oq_block}"
        )

    # --- Decisions ---
    decisions_dir = skilllayer_dir / "decisions"
    all_files = sorted(decisions_dir.glob("*.md")) if decisions_dir.exists() else []
    total = len(all_files)
    last_three = all_files[-3:]
    d_lines: list[str] = []
    for df in reversed(last_three):
        d_meta, _ = parse_frontmatter(df.read_text(encoding="utf-8"))
        d_id = str(d_meta.get("id", df.stem[:4]))
        raw_stem = df.stem
        title_part = raw_stem[5:].replace("-", " ") if len(raw_stem) > 5 else raw_stem
        d_status = str(d_meta.get("status", "proposed"))
        d_created = str(d_meta.get("created", ""))[:10]
        d_lines.append(f"- {d_id} {title_part} · {d_status} · {d_created}")
    d_block = "\n".join(d_lines) if d_lines else "  (none)"
    sections.append(
        f"## Decisions · TrackDecisionLog — {total} total, last 3\n"
        f"{d_block}\n"
        f"full log: decisions/"
    )

    # --- Preferences ---
    prefs_file = skilllayer_dir / "preferences.md"
    if prefs_file.exists():
        _, prefs_body = parse_frontmatter(prefs_file.read_text(encoding="utf-8"))
        digest_lines: list[str] = []
        current_domain: str | None = None
        added_per_domain: set[str] = set()
        for line in prefs_body.splitlines():
            stripped = line.strip()
            if stripped.startswith("## "):
                current_domain = stripped[3:].strip().lower()
                added_per_domain = set()
            elif stripped.startswith("- ") and current_domain:
                key_val = stripped[2:].strip()
                if current_domain not in added_per_domain:
                    digest_lines.append(f"- {current_domain}: {key_val}")
                    added_per_domain.add(current_domain)
        digest = "\n".join(digest_lines) if digest_lines else "  (none)"
        sections.append(
            f"## Preferences · RememberUserPreferences\n"
            f"{digest}\n"
            f"full: preferences.md"
        )

    meta = {"schema": SCHEMA_VERSION, "updated": _utc_iso()}
    return write_frontmatter(meta, "\n\n".join(sections))


def write_index(skilllayer_dir: Path) -> None:
    """Write the regenerated INDEX.md to disk."""
    index_file = skilllayer_dir / "INDEX.md"
    index_file.write_text(regenerate_index(skilllayer_dir), encoding="utf-8")


# ---------------------------------------------------------------------------
# SaveContextSnapshot
# ---------------------------------------------------------------------------

def save_context_snapshot(
    skilllayer_dir: Path,
    state: str,
    open_questions: list[str],
) -> dict[str, Any]:
    """Write context/latest.md (latest-wins). Rotate previous to history/."""
    skilllayer_dir.mkdir(parents=True, exist_ok=True)
    context_dir = skilllayer_dir / "context"
    context_dir.mkdir(exist_ok=True)
    history_dir = context_dir / "history"
    history_dir.mkdir(exist_ok=True)

    latest = context_dir / "latest.md"

    # Rotate existing latest to history
    if latest.exists():
        ts = _utc_filename_ts()
        history_dest = history_dir / f"{ts}.md"
        latest.rename(history_dest)

    # Prune history beyond HISTORY_KEEP
    history_files = sorted(history_dir.glob("*.md"))
    for old_file in history_files[:-HISTORY_KEEP]:
        old_file.unlink()
    history_count = len(list(history_dir.glob("*.md")))

    # Build new latest.md
    oq_lines = "\n".join(f"- {q}" for q in open_questions) if open_questions else "(none)"
    body = f"## State\n{state}\n\n## Open Questions\n{oq_lines}\n"
    now = _utc_iso()
    meta: dict[str, Any] = {
        "schema": SCHEMA_VERSION,
        "type": "context_snapshot",
        "workflow": "SaveContextSnapshotWorkflow",
        "id": "latest",
        "created": now,
        "updated": now,
    }
    latest.write_text(write_frontmatter(meta, body), encoding="utf-8")
    write_index(skilllayer_dir)

    return {
        "workflow": "SaveContextSnapshotWorkflow",
        "context_file": str(latest),
        "history_count": history_count,
        "open_questions": open_questions,
        "summary": f"Context snapshot saved. {len(open_questions)} open question(s). {history_count} history file(s) retained.",
    }


# ---------------------------------------------------------------------------
# TrackDecisionLog
# ---------------------------------------------------------------------------

def track_decision(
    skilllayer_dir: Path,
    title: str,
    context: str,
    decision: str,
    reasoning: str,
    consequences: str,
    status: str = "proposed",
    related_files: list[str] | None = None,
    supersedes: str | None = None,
) -> dict[str, Any]:
    """Append an immutable ADR file to decisions/."""
    if status not in ("proposed", "accepted", "superseded", "deprecated"):
        status = "proposed"

    skilllayer_dir.mkdir(parents=True, exist_ok=True)
    decisions_dir = skilllayer_dir / "decisions"
    decisions_dir.mkdir(exist_ok=True)

    decision_id = claim_next_decision_id(skilllayer_dir)
    slug = _slugify(title)
    filename = f"{decision_id}-{slug}.md"
    decision_file = decisions_dir / filename

    now = _utc_iso()
    meta: dict[str, Any] = {
        "schema": SCHEMA_VERSION,
        "type": "decision",
        "workflow": "TrackDecisionLogWorkflow",
        "id": decision_id,
        "status": status,
        "supersedes": supersedes,
        "created": now,
        "updated": now,
    }
    if related_files:
        meta["related_files"] = related_files

    body = (
        f"# {title}\n\n"
        f"## Context\n{context}\n\n"
        f"## Decision\n{decision}\n\n"
        f"## Reasoning\n{reasoning}\n\n"
        f"## Consequences\n{consequences}\n"
    )
    decision_file.write_text(write_frontmatter(meta, body), encoding="utf-8")

    # If this supersedes an older decision, flip its status
    if supersedes:
        old_files = list(decisions_dir.glob(f"{supersedes}-*.md"))
        for old_file in old_files:
            old_meta, old_body = parse_frontmatter(old_file.read_text(encoding="utf-8"))
            old_meta["status"] = "superseded"
            old_meta["superseded_by"] = decision_id
            old_file.write_text(write_frontmatter(old_meta, old_body), encoding="utf-8")

    write_index(skilllayer_dir)

    return {
        "workflow": "TrackDecisionLogWorkflow",
        "decision_id": decision_id,
        "file": str(decision_file),
        "title": title,
        "status": status,
        "supersedes": supersedes,
        "summary": f"Decision {decision_id} recorded: {title!r} ({status}).",
    }


# ---------------------------------------------------------------------------
# RememberUserPreferences
# ---------------------------------------------------------------------------

def remember_preferences(
    skilllayer_dir: Path,
    preferences: dict[str, dict[str, str]],
) -> dict[str, Any]:
    """Upsert preferences.md by domain. Last-writer-wins per key."""
    skilllayer_dir.mkdir(parents=True, exist_ok=True)
    prefs_file = skilllayer_dir / "preferences.md"

    # Load existing preferences
    existing: dict[str, dict[str, str]] = {}
    if prefs_file.exists():
        _, body = parse_frontmatter(prefs_file.read_text(encoding="utf-8"))
        current_domain: str | None = None
        for line in body.splitlines():
            stripped = line.strip()
            if stripped.startswith("## "):
                current_domain = stripped[3:].strip().lower()
                existing.setdefault(current_domain, {})
            elif stripped.startswith("- ") and current_domain:
                if ": " in stripped[2:]:
                    k, _, v = stripped[2:].partition(": ")
                    existing[current_domain][k.strip()] = v.strip()

    # Merge (last-writer-wins per key within domain)
    for domain, keys in preferences.items():
        domain_lower = domain.lower()
        existing.setdefault(domain_lower, {})
        existing[domain_lower].update(keys)

    # Serialize preferences.md
    sections_updated = sorted(existing.keys())
    body_parts: list[str] = []
    for domain in sections_updated:
        lines = [f"## {domain}"]
        for k, v in sorted(existing[domain].items()):
            lines.append(f"- {k}: {v}")
        body_parts.append("\n".join(lines))
    body = "\n\n".join(body_parts) + "\n"

    now = _utc_iso()
    meta: dict[str, Any] = {
        "schema": SCHEMA_VERSION,
        "type": "preferences",
        "workflow": "RememberUserPreferencesWorkflow",
        "id": "preferences",
        "updated": now,
    }
    prefs_file.write_text(write_frontmatter(meta, body), encoding="utf-8")
    write_index(skilllayer_dir)

    return {
        "workflow": "RememberUserPreferencesWorkflow",
        "preferences_file": str(prefs_file),
        "sections_updated": sections_updated,
        "summary": f"Preferences updated. Sections: {', '.join(sections_updated)}.",
    }


# ---------------------------------------------------------------------------
# RehydrateContext (read-only)
# ---------------------------------------------------------------------------

def rehydrate_context(
    skilllayer_dir: Path,
    *,
    full_context: bool = False,
    decision_id: str | None = None,
    full_preferences: bool = False,
) -> dict[str, Any]:
    """Read-only. Returns INDEX.md digest plus optional drill-down content."""
    index_file = skilllayer_dir / "INDEX.md"
    if not index_file.exists():
        return {
            "workflow": "RehydrateContextWorkflow",
            "index": None,
            "context": None,
            "decision": None,
            "preferences": None,
            "error_code": "no_memory_store",
            "summary": "No .skilllayer/ memory store found at this repository root.",
        }

    index_content = index_file.read_text(encoding="utf-8")
    context_content: str | None = None
    decision_content: str | None = None
    preferences_content: str | None = None

    if full_context:
        latest = skilllayer_dir / "context" / "latest.md"
        if latest.exists():
            context_content = latest.read_text(encoding="utf-8")

    if decision_id is not None:
        decisions_dir = skilllayer_dir / "decisions"
        matches = list(decisions_dir.glob(f"{decision_id}-*.md")) if decisions_dir.exists() else []
        if matches:
            decision_content = matches[0].read_text(encoding="utf-8")
        else:
            decision_content = f"(decision {decision_id} not found)"

    if full_preferences:
        prefs_file = skilllayer_dir / "preferences.md"
        if prefs_file.exists():
            preferences_content = prefs_file.read_text(encoding="utf-8")

    has_extras = any(x is not None for x in (context_content, decision_content, preferences_content))
    summary = "Memory rehydrated from INDEX.md."
    if has_extras:
        parts = []
        if context_content:
            parts.append("full context")
        if decision_content:
            parts.append(f"decision {decision_id}")
        if preferences_content:
            parts.append("full preferences")
        summary = f"Memory rehydrated: index + {', '.join(parts)}."

    return {
        "workflow": "RehydrateContextWorkflow",
        "index": index_content,
        "context": context_content,
        "decision": decision_content,
        "preferences": preferences_content,
        "error_code": None,
        "summary": summary,
    }
